sudo: false
language: node_js
node_js:
  - 8
cache:
  yarn: true
  directories:
    - bower_components
    - node_modules
branches:
  only:
    - master
install:
  - npm install -g npm@latest
  - npm install -g yarn bower
  - yarn
  - bower install
before_script:
  - npm prune
script:
  - yarn validate
  - yarn build
